language: crystal

before_install:
  - wget 'https://github.com/ImageMagick/ImageMagick/archive/7.0.4-1.tar.gz'
  - tar xvfz 7.0.4-1.tar.gz
  - cd ImageMagick-7.0.4-1
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig

# Uncomment the following if you'd like Travis to run specs and check code formatting
# script:
#   - crystal spec
#   - crystal tool format --check
