lib LibMagick
  fun getImageFromMagickWand = GetImageFromMagickWand(wand : MagickWand*) : Image*
  fun magickAdaptiveBlurImage = MagickAdaptiveBlurImage(wand : MagickWand*, radius : LibC::Double, sigma : LibC::Double) : Bool
  fun magickAdaptiveResizeImage = MagickAdaptiveResizeImage(wand : MagickWand*, columns : LibC::SizeT, rows : LibC::SizeT) : Bool
  fun magickAdaptiveSharpenImage = MagickAdaptiveSharpenImage(wand : MagickWand*, radius : LibC::Double, sigma : LibC::Double) : Bool
  fun magickAdaptiveThresholdImage = MagickAdaptiveThresholdImage(wand : MagickWand*, width : LibC::SizeT, height : LibC::SizeT, bias : LibC::Double) : Bool
  fun magickAddImage = MagickAddImage(wand : MagickWand*, add_wand : MagickWand*) : Bool
  fun magickAddNoiseImage = MagickAddNoiseImage(wand : MagickWand*, noise_type : NoiseType, attenuate : LibC::Double) : Bool
  fun magickAffineTransformImage = MagickAffineTransformImage(wand : MagickWand*, drawing_wand : DrawingWand*) : Bool
  fun magickAnnotateImage = MagickAnnotateImage(wand : MagickWand*, drawing_wand : DrawingWand*, x : LibC::Double, y : LibC::Double, angle : LibC::Double, text : LibC::Char*) : Bool
  fun magickAnimateImages = MagickAnimateImages(wand : MagickWand*, server_name : LibC::Char*) : Bool
  fun magickAppendImages = MagickAppendImages(wand : MagickWand*, stack : Bool) : MagickWand*
  fun magickAutoGammaImage = MagickAutoGammaImage(wand : MagickWand*) : Bool
  fun magickAutoLevelImage = MagickAutoLevelImage(wand : MagickWand*) : Bool
  fun magickAutoOrientImage = MagickAutoOrientImage(wand : MagickWand*) : Bool
  fun magickAutoThresholdImage = MagickAutoThresholdImage(wand : MagickWand*, method : AutoThresholdMethod) : Bool
  fun magickBlackThresholdImage = MagickBlackThresholdImage(wand : MagickWand*, threshold : PixelWand*) : Bool
  fun magickBlueShiftImage = MagickBlueShiftImage(wand : MagickWand*, factor : LibC::Double) : Bool
  fun magickBlurImage = MagickBlurImage(wand : MagickWand*, radius : LibC::Double, sigma : LibC::Double) : Bool
  fun magickBorderImage = MagickBorderImage(wand : MagickWand*, bordercolor : PixelWand*, width : LibC::SizeT, height : LibC::SizeT, compose : CompositeOperator) : Bool
  fun magickBrightnessContrastImage = MagickBrightnessContrastImage(wand : MagickWand*, brightness : LibC::Double, contrast : LibC::Double) : Bool
  fun magickCannyEdgeImage = MagickCannyEdgeImage(wand : MagickWand*, radius : LibC::Double, sigma : LibC::Double, lower_percent : LibC::Double, upper_percent : LibC::Double) : Bool
  fun magickChannelFxImage = MagickChannelFxImage(wand : MagickWand*, expression : LibC::Char*) : MagickWand*
  fun magickCharcoalImage = MagickCharcoalImage(wand : MagickWand*, radius : LibC::Double, sigma : LibC::Double) : Bool
  fun magickChopImage = MagickChopImage(wand : MagickWand*, width : LibC::SizeT, height : LibC::SizeT, x : LibC::SSizeT, y : LibC::SSizeT) : Bool
  fun magickCLAHEImage = MagickCLAHEImage(wand : MagickWand*, width : LibC::SizeT, height : LibC::SizeT, number_bins : LibC::Double, clip_limit : LibC::Double) : Bool
  fun magickClampImage = MagickClampImage(wand : MagickWand*) : Bool
  fun magickClipImage = MagickClipImage(wand : MagickWand*) : Bool
  fun magickClipImagePath = MagickClipImagePath(wand : MagickWand*, pathname : LibC::Char*, inside : Bool) : Bool
  fun magickClutImage = MagickClutImage(wand : MagickWand*, clut_wand : MagickWand*, method : PixelInterpolateMethod) : Bool
  fun magickCoalesceImages = MagickCoalesceImages(wand : MagickWand*) : MagickWand*
  fun magickColorDecisionListImage = MagickColorDecisionListImage(wand : MagickWand*, color_correction_collection : LibC::Char*) : Bool
  fun magickColorizeImage = MagickColorizeImage(wand : MagickWand*, colorize : PixelWand*, blend : PixelWand*) : Bool
  fun magickColorMatrixImage = MagickColorMatrixImage(wand : MagickWand*, color_matrix : KernelInfo*) : Bool
  fun magickCombineImages = MagickCombineImages(wand : MagickWand*, colorspace : ColorspaceType) : MagickWand*
  fun magickCommentImage = MagickCommentImage(wand : MagickWand*, comment : LibC::Char*) : Bool
  fun magickCompareImagesLayers = MagickCompareImagesLayers(wand : MagickWand*, method : LayerMethod) : MagickWand*
  fun magickCompareImages = MagickCompareImages(wand : MagickWand*, reference : MagickWand*, metric : MetricType, distortion : LibC::Double*) : MagickWand*
  fun magickComplexImages = MagickComplexImages(wand : MagickWand*, op : ComplexOperator) : MagickWand*
  fun magickCompositeImage = MagickCompositeImage(wand : MagickWand*, source_wand : MagickWand*, compose : CompositeOperator, clip_to_self : Bool, x : LibC::SSizeT, y : LibC::SSizeT) : Bool
  fun magickCompositeImageGravity = MagickCompositeImageGravity(wand : MagickWand*, source_wand : MagickWand*, compose : CompositeOperator, gravity : GravityType) : Bool
  fun magickCompositeLayers = MagickCompositeLayers(wand : MagickWand*, source_wand : MagickWand*, compose : CompositeOperator, x : LibC::SSizeT, y : LibC::SSizeT) : Bool
  fun magickConnectedComponentsImage = MagickConnectedComponentsImage(wand : MagickWand*, connectivity : LibC::SizeT, objects : CCObjectInfo**) : Bool
  fun magickContrastImage = MagickContrastImage(wand : MagickWand*, sharpen : Bool) : Bool
  fun magickContrastStretchImage = MagickContrastStretchImage(wand : MagickWand*, black_point : LibC::Double, white_point : LibC::Double) : Bool
  fun magickConvolveImage = MagickConvolveImage(wand : MagickWand*, kernel : KernelInfo*) : Bool
  fun magickCropImage = MagickCropImage(wand : MagickWand*, width : LibC::SizeT, height : LibC::SizeT, x : LibC::SSizeT, y : LibC::SSizeT) : Bool
  fun magickCycleColormapImage = MagickCycleColormapImage(wand : MagickWand*, displace : LibC::SSizeT) : Bool
  fun magickConstituteImage = MagickConstituteImage(wand : MagickWand*, columns : LibC::SizeT, rows : LibC::SizeT, map : LibC::Char*, storage : StorageType, pixels : Void*) : Bool
  fun magickDecipherImage = MagickDecipherImage(wand : MagickWand*, passphrase : LibC::Char*) : Bool
  fun magickDeconstructImages = MagickDeconstructImages(wand : MagickWand*) : MagickWand*
  fun magickDeskewImage = MagickDeskewImage(wand : MagickWand*, threshold : LibC::Double) : Bool
  fun magickDespeckleImage = MagickDespeckleImage(wand : MagickWand*) : Bool
  fun magickDestroyImage = MagickDestroyImage(image : Image*) : Image*
  fun magickDisplayImage = MagickDisplayImage(wand : MagickWand*, server_name : LibC::Char*) : Bool
  fun magickDisplayImages = MagickDisplayImages(wand : MagickWand*, server_name : LibC::Char*) : Bool
  fun magickDistortImage = MagickDistortImage(wand : MagickWand*, method : DistortMethod, number_arguments : LibC::SizeT, arguments : LibC::Double*, bestfit : Bool) : Bool
  fun magickDrawImage = MagickDrawImage(wand : MagickWand*, drawing_wand : DrawingWand*) : Bool
  fun magickEdgeImage = MagickEdgeImage(wand : MagickWand*, radius : LibC::Double) : Bool
  fun magickEmbossImage = MagickEmbossImage(wand : MagickWand*, radius : LibC::Double, sigma : LibC::Double) : Bool
  fun magickEncipherImage = MagickEncipherImage(wand : MagickWand*, passphrase : LibC::Char*) : Bool
  fun magickEnhanceImage = MagickEnhanceImage(wand : MagickWand*) : Bool
  fun magickEqualizeImage = MagickEqualizeImage(wand : MagickWand*) : Bool
  fun magickEvaluateImages = MagickEvaluateImages(wand : MagickWand*, op : MagickEvaluateOperator) : MagickWand*
  fun magickEvaluateImage = MagickEvaluateImage(wand : MagickWand*, op : MagickEvaluateOperator, value : LibC::Double) : Bool
  fun magickExportImagePixels = MagickExportImagePixels(wand : MagickWand*, x : LibC::SSizeT, y : LibC::SSizeT, columns : LibC::SizeT, rows : LibC::SizeT, map : LibC::Char*, storage : StorageType, pixels : Void*) : Bool
  fun magickExtentImage = MagickExtentImage(wand : MagickWand*, width : LibC::SizeT, height : LibC::SizeT, x : LibC::SSizeT, y : LibC::SSizeT) : Bool
  fun magickFlipImage = MagickFlipImage(wand : MagickWand*) : Bool
  fun magickFloodfillPaintImage = MagickFloodfillPaintImage(wand : MagickWand*, fill : PixelWand*, fuzz : LibC::Double, bordercolor : PixelWand*, x : LibC::SSizeT, y : LibC::SSizeT, invert : Bool) : Bool
  fun magickFlopImage = MagickFlopImage(wand : MagickWand*) : Bool
  fun magickForwardFourierTransformImage = MagickForwardFourierTransformImage(wand : MagickWand*, magnitude : Bool) : Bool
  fun magickFrameImage = MagickFrameImage(wand : MagickWand*, matte_color : PixelWand*, width : LibC::SizeT, height : LibC::SizeT, inner_bevel : LibC::SSizeT, outer_bevel : LibC::SSizeT, compose : CompositeOperator) : Bool
  fun magickFunctionImage = MagickFunctionImage(wand : MagickWand*, function : MagickFunction, number_arguments : LibC::SizeT, arguments : LibC::Double*) : Bool
  fun magickFxImage = MagickFxImage(wand : MagickWand*, expression : LibC::Char*) : MagickWand*
  fun magickGammaImage = MagickGammaImage(wand : MagickWand*, gamma : LibC::Double) : Bool
  fun magickGaussianBlurImage = MagickGaussianBlurImage(wand : MagickWand*, radius : LibC::Double, sigma : LibC::Double) : Bool
  fun magickGetImage = MagickGetImage(wand : MagickWand*) : MagickWand*
  fun magickGetImageAlphaChannel = MagickGetImageAlphaChannel(wand : MagickWand*) : Bool
  fun magickGetImageMask = MagickGetImageMask(wand : MagickWand*, type : PixelMask) : MagickWand*
  fun magickGetImageBackgroundColor = MagickGetImageBackgroundColor(wand : MagickWand*, background_color : PixelWand*) : Bool
  fun magickGetImageBlob = MagickGetImageBlob(wand : MagickWand*, length : LibC::SizeT*) : LibC::UChar*
  fun magickGetImagesBlob = MagickGetImagesBlob(wand : MagickWand*, length : LibC::SizeT*) : LibC::UChar*
  fun magickGetImageBluePrimary = MagickGetImageBluePrimary(wand : MagickWand*, x : LibC::Double*, y : LibC::Double*, z : LibC::Double*) : Bool
  fun magickGetImageBorderColor = MagickGetImageBorderColor(wand : MagickWand*, border_color : PixelWand*) : Bool
  fun magickGetImageFeatures = MagickGetImageFeatures(wand : MagickWand*, distance : LibC::SizeT) : ChannelFeatures*
  fun magickGetImageKurtosis = MagickGetImageKurtosis(wand : MagickWand*, kurtosis : LibC::Double*, skewness : LibC::Double*) : Bool
  fun magickGetImageMean = MagickGetImageMean(wand : MagickWand*, mean : LibC::Double*, standard_deviation : LibC::Double*) : Bool
  fun magickGetImageRange = MagickGetImageRange(wand : MagickWand*, minima : LibC::Double*, maxima : LibC::Double*) : Bool
  fun magickGetImageStatistics = MagickGetImageStatistics(wand : MagickWand*) : ChannelStatistics*
  fun magickGetImageColormapColor = MagickGetImageColormapColor(wand : MagickWand*, index : LibC::SizeT, color : PixelWand*) : Bool
  fun magickGetImageColors = MagickGetImageColors(wand : MagickWand*) : LibC::SizeT
  fun magickGetImageColorspace = MagickGetImageColorspace(wand : MagickWand*) : ColorspaceType
  fun magickGetImageCompose = MagickGetImageCompose(wand : MagickWand*) : CompositeOperator
  fun magickGetImageCompression = MagickGetImageCompression(wand : MagickWand*) : CompressionType
  fun magickGetImageCompressionQuality = MagickGetImageCompressionQuality(wand : MagickWand*) : LibC::SizeT
  fun magickGetImageDelay = MagickGetImageDelay(wand : MagickWand*) : LibC::SizeT
  fun magickGetImageDepth = MagickGetImageDepth(wand : MagickWand*) : LibC::SizeT
  fun magickGetImageDispose = MagickGetImageDispose(wand : MagickWand*) : DisposeType
  fun magickGetImageDistortion = MagickGetImageDistortion(wand : MagickWand*, reference : MagickWand*, metric : MetricType, distortion : LibC::Double*) : Bool
  fun magickGetImageDistortions = MagickGetImageDistortions(wand : MagickWand*, reference : MagickWand*, metric : MetricType) : LibC::Double*
  fun magickGetImageEndian = MagickGetImageEndian(wand : MagickWand*) : EndianType
  fun magickGetImageFilename = MagickGetImageFilename(wand : MagickWand*) : LibC::Char*
  fun magickGetImageFormat = MagickGetImageFormat(wand : MagickWand*) : LibC::Char*
  fun magickGetImageFuzz = MagickGetImageFuzz(wand : MagickWand*) : LibC::Double
  fun magickGetImageGamma = MagickGetImageGamma(wand : MagickWand*) : LibC::Double
  fun magickGetImageGravity = MagickGetImageGravity(wand : MagickWand*) : GravityType
  fun magickGetImageGreenPrimary = MagickGetImageGreenPrimary(wand : MagickWand*, x : LibC::Double*, y : LibC::Double*, z : LibC::Double*) : Bool
  fun magickGetImageHeight = MagickGetImageHeight(wand : MagickWand*) : LibC::SizeT
  fun magickGetImageHistogram = MagickGetImageHistogram(wand : MagickWand*, number_colors : LibC::SizeT*) : PixelWand**
  fun magickGetImageInterlaceScheme = MagickGetImageInterlaceScheme(wand : MagickWand*) : InterlaceType
  fun magickGetImageInterpolateMethod = MagickGetImageInterpolateMethod(wand : MagickWand*) : PixelInterpolateMethod
  fun magickGetImageIterations = MagickGetImageIterations(wand : MagickWand*) : LibC::SizeT
  fun magickGetImageLength = MagickGetImageLength(wand : MagickWand*, length : MagickSizeType*) : Bool
  fun magickGetImageMatteColor = MagickGetImageMatteColor(wand : MagickWand*, matte_color : PixelWand*) : Bool
  fun magickGetImageOrientation = MagickGetImageOrientation(wand : MagickWand*) : OrientationType
  fun magickGetImagePage = MagickGetImagePage(wand : MagickWand*, width : LibC::SizeT*, height : LibC::SizeT*, x : LibC::SSizeT*, y : LibC::SSizeT*) : Bool
  fun magickGetImagePixelColor = MagickGetImagePixelColor(wand : MagickWand*, x : LibC::SSizeT, y : LibC::SSizeT, color : PixelWand*) : Bool
  fun magickGetImageRedPrimary = MagickGetImageRedPrimary(wand : MagickWand*, x : LibC::Double*, y : LibC::Double*, z : LibC::Double*) : Bool
  fun magickGetImageRegion = MagickGetImageRegion(wand : MagickWand*, width : LibC::SizeT, height : LibC::SizeT, x : LibC::SSizeT, y : LibC::SSizeT) : MagickWand*
  fun magickGetImageRenderingIntent = MagickGetImageRenderingIntent(wand : MagickWand*) : RenderingIntent
  fun magickGetImageResolution = MagickGetImageResolution(wand : MagickWand*, x : LibC::Double*, y : LibC::Double*) : Bool
  fun magickGetImageScene = MagickGetImageScene(wand : MagickWand*) : LibC::SizeT
  fun magickGetImageSignature = MagickGetImageSignature(wand : MagickWand*) : LibC::Char*
  fun magickGetImageTicksPerSecond = MagickGetImageTicksPerSecond(wand : MagickWand*) : LibC::SizeT
  fun magickGetImageType = MagickGetImageType(wand : MagickWand*) : ImageType
  fun magickGetImageUnits = MagickGetImageUnits(wand : MagickWand*) : ResolutionType
  fun magickGetImageVirtualPixelMethod = MagickGetImageVirtualPixelMethod(wand : MagickWand*) : VirtualPixelMethod
  fun magickGetImageWhitePoint = MagickGetImageWhitePoint(wand : MagickWand*, x : LibC::Double*, y : LibC::Double*, z : LibC::Double*) : Bool
  fun magickGetImageWidth = MagickGetImageWidth(wand : MagickWand*) : LibC::SizeT
  fun magickGetNumberImages = MagickGetNumberImages(wand : MagickWand*) : LibC::SizeT
  fun magickGetImageTotalInkDensity = MagickGetImageTotalInkDensity(wand : MagickWand*) : LibC::Double
  fun magickHaldClutImage = MagickHaldClutImage(wand : MagickWand*, hald_wand : MagickWand*) : Bool
  fun magickHasNextImage = MagickHasNextImage(wand : MagickWand*) : Bool
  fun magickHasPreviousImage = MagickHasPreviousImage(wand : MagickWand*) : Bool
  fun magickHoughLineImage = MagickHoughLineImage(wand : MagickWand*, width : LibC::SizeT, height : LibC::SizeT, threshold : LibC::SizeT) : Bool
  fun magickIdentifyImage = MagickIdentifyImage(wand : MagickWand*) : LibC::Char*
  fun magickIdentifyImageType = MagickIdentifyImageType(wand : MagickWand*) : ImageType
  fun magickImplodeImage = MagickImplodeImage(wand : MagickWand*, amount : LibC::Double, method : PixelInterpolateMethod) : Bool
  fun magickImportImagePixels = MagickImportImagePixels(wand : MagickWand*, x : LibC::SSizeT, y : LibC::SSizeT, columns : LibC::SizeT, rows : LibC::SizeT, map : LibC::Char*, storage : StorageType, pixels : Void*) : Bool
  fun magickInterpolativeResizeImage = MagickInterpolativeResizeImage(wand : MagickWand*, columns : LibC::SizeT, rows : LibC::SizeT, method : PixelInterpolateMethod) : Bool
  fun magickInverseFourierTransformImage = MagickInverseFourierTransformImage(magnitude_wand : MagickWand*, phase_wand : MagickWand*, magnitude : Bool) : Bool
  fun magickKuwaharaImage = MagickKuwaharaImage(wand : MagickWand*, radius : LibC::Double, sigma : LibC::Double) : Bool
  fun magickLabelImage = MagickLabelImage(wand : MagickWand*, label : LibC::Char*) : Bool
  fun magickLevelImage = MagickLevelImage(wand : MagickWand*, black_point : LibC::Double, gamma : LibC::Double, white_point : LibC::Double) : Bool
  fun magickLevelImageColors = MagickLevelImageColors(wand : MagickWand*, black_color : PixelWand*, white_color : PixelWand*, invert : Bool) : Bool
  fun magickLevelizeImage = MagickLevelizeImage(wand : MagickWand*, black_point : LibC::Double, gamma : LibC::Double, white_point : LibC::Double) : Bool
  fun magickLinearStretchImage = MagickLinearStretchImage(wand : MagickWand*, black_point : LibC::Double, white_point : LibC::Double) : Bool
  fun magickLiquidRescaleImage = MagickLiquidRescaleImage(wand : MagickWand*, columns : LibC::SizeT, rows : LibC::SizeT, delta_x : LibC::Double, rigidity : LibC::Double) : Bool
  fun magickLocalContrastImage = MagickLocalContrastImage(wand : MagickWand*, radius : LibC::Double, strength : LibC::Double) : Bool
  fun magickMagnifyImage = MagickMagnifyImage(wand : MagickWand*) : Bool
  fun magickMeanShiftImage = MagickMeanShiftImage(wand : MagickWand*, width : LibC::SizeT, height : LibC::SizeT, color_distance : LibC::Double) : Bool
  fun magickMergeImageLayers = MagickMergeImageLayers(wand : MagickWand*, method : LayerMethod) : MagickWand*
  fun magickMinifyImage = MagickMinifyImage(wand : MagickWand*) : Bool
  fun magickModulateImage = MagickModulateImage(wand : MagickWand*, brightness : LibC::Double, saturation : LibC::Double, hue : LibC::Double) : Bool
  fun magickMontageImage = MagickMontageImage(wand : MagickWand*, drawing_wand : DrawingWand*, tile_geometry : LibC::Char*, thumbnail_geometry : LibC::Char*, mode : MontageMode, frame : LibC::Char*) : MagickWand*
  fun magickMorphImages = MagickMorphImages(wand : MagickWand*, number_frames : LibC::SizeT) : MagickWand*
  fun magickMorphologyImage = MagickMorphologyImage(wand : MagickWand*, method : MorphologyMethod, iterations : LibC::SSizeT, kernel : KernelInfo*) : Bool
  fun magickMotionBlurImage = MagickMotionBlurImage(wand : MagickWand*, radius : LibC::Double, sigma : LibC::Double, angle : LibC::Double) : Bool
  fun magickNegateImage = MagickNegateImage(wand : MagickWand*, gray : Bool) : Bool
  fun magickNewImage = MagickNewImage(wand : MagickWand*, width : LibC::SizeT, height : LibC::SizeT, background : PixelWand*) : Bool
  fun magickNextImage = MagickNextImage(wand : MagickWand*) : Bool
  fun magickNormalizeImage = MagickNormalizeImage(wand : MagickWand*) : Bool
  fun magickOilPaintImage = MagickOilPaintImage(wand : MagickWand*, radius : LibC::Double, sigma : LibC::Double) : Bool
  fun magickOpaquePaintImage = MagickOpaquePaintImage(wand : MagickWand*, target : PixelWand*, fill : PixelWand*, fuzz : LibC::Double, invert : Bool) : Bool
  fun magickOptimizeImageLayers = MagickOptimizeImageLayers(wand : MagickWand*) : MagickWand*
  fun magickOptimizeImageTransparency = MagickOptimizeImageTransparency(wand : MagickWand*) : Bool
  fun magickOrderedDitherImage = MagickOrderedDitherImage(wand : MagickWand*, threshold_map : LibC::Char*) : Bool
  fun magickPingImage = MagickPingImage(wand : MagickWand*, filename : LibC::Char*) : Bool
  fun magickPingImageBlob = MagickPingImageBlob(wand : MagickWand*, blob : Void*, length : LibC::SizeT) : Bool
  fun magickPingImageFile = MagickPingImageFile(wand : MagickWand*, file : LibStd::File*) : Bool
  fun magickPolaroidImage = MagickPolaroidImage(wand : MagickWand*, drawing_wand : DrawingWand*, caption : LibC::Char*, angle : LibC::Double, method : PixelInterpolateMethod) : Bool
  fun magickPolynomialImage = MagickPolynomialImage(wand : MagickWand*, number_terms : LibC::SizeT, terms : LibC::Double*) : Bool
  fun magickPosterizeImage = MagickPosterizeImage(wand : MagickWand*, levels : LibC::SizeT, dither : DitherMethod) : Bool
  fun magickPreviewImages = MagickPreviewImages(wand : MagickWand*, preview : PreviewType) : MagickWand*
  fun magickPreviousImage = MagickPreviousImage(wand : MagickWand*) : Bool
  fun magickQuantizeImage = MagickQuantizeImage(wand : MagickWand*, number_colors : LibC::SizeT, colorspace : ColorspaceType, treedepth : LibC::SizeT, dither_method : DitherMethod, measure_error : Bool) : Bool
  fun magickQuantizeImages = MagickQuantizeImages(wand : MagickWand*, number_colors : LibC::SizeT, colorspace : ColorspaceType, treedepth : LibC::SizeT, dither_method : DitherMethod, measure_error : Bool) : Bool
  fun magickRangeThresholdImage = MagickRangeThresholdImage(wand : MagickWand*, low_black : LibC::Double, low_white : LibC::Double, high_white : LibC::Double, high_black : LibC::Double) : Bool
  fun magickRotationalBlurImage = MagickRotationalBlurImage(wand : MagickWand*, angle : LibC::Double) : Bool
  fun magickRaiseImage = MagickRaiseImage(wand : MagickWand*, width : LibC::SizeT, height : LibC::SizeT, x : LibC::SSizeT, y : LibC::SSizeT, raise : Bool) : Bool
  fun magickRandomThresholdImage = MagickRandomThresholdImage(wand : MagickWand*, low : LibC::Double, high : LibC::Double) : Bool
  fun magickReadImage = MagickReadImage(wand : MagickWand*, filename : LibC::Char*) : Bool
  fun magickReadImageBlob = MagickReadImageBlob(wand : MagickWand*, blob : Void*, length : LibC::SizeT) : Bool
  fun magickReadImageFile = MagickReadImageFile(wand : MagickWand*, file : LibStd::File*) : Bool
  fun magickRemapImage = MagickRemapImage(wand : MagickWand*, remap_wand : MagickWand*, dither_method : DitherMethod) : Bool
  fun magickRemoveImage = MagickRemoveImage(wand : MagickWand*) : Bool
  fun magickResampleImage = MagickResampleImage(wand : MagickWand*, x_resolution : LibC::Double, y_resolution : LibC::Double, filter : FilterType) : Bool
  fun magickResetImagePage = MagickResetImagePage(wand : MagickWand*, page : LibC::Char*) : Bool
  fun magickResizeImage = MagickResizeImage(wand : MagickWand*, columns : LibC::SizeT, rows : LibC::SizeT, filter : FilterType) : Bool
  fun magickRollImage = MagickRollImage(wand : MagickWand*, x : LibC::SSizeT, y : LibC::SSizeT) : Bool
  fun magickRotateImage = MagickRotateImage(wand : MagickWand*, background : PixelWand*, degrees : LibC::Double) : Bool
  fun magickSampleImage = MagickSampleImage(wand : MagickWand*, columns : LibC::SizeT, rows : LibC::SizeT) : Bool
  fun magickScaleImage = MagickScaleImage(wand : MagickWand*, columns : LibC::SizeT, rows : LibC::SizeT) : Bool
  fun magickSegmentImage = MagickSegmentImage(wand : MagickWand*, colorspace : ColorspaceType, verbose : Bool, cluster_threshold : LibC::Double, smooth_threshold : LibC::Double) : Bool
  fun magickSelectiveBlurImage = MagickSelectiveBlurImage(wand : MagickWand*, radius : LibC::Double, sigma : LibC::Double, threshold : LibC::Double) : Bool
  fun magickSeparateImage = MagickSeparateImage(wand : MagickWand*, channel : ChannelType) : Bool
  fun magickSepiaToneImage = MagickSepiaToneImage(wand : MagickWand*, threshold : LibC::Double) : Bool
  fun magickSetImage = MagickSetImage(wand : MagickWand*, set_wand : MagickWand*) : Bool
  fun magickSetImageAlphaChannel = MagickSetImageAlphaChannel(wand : MagickWand*, alpha_type : AlphaChannelOption) : Bool
  fun magickSetImageBackgroundColor = MagickSetImageBackgroundColor(wand : MagickWand*, background : PixelWand*) : Bool
  fun magickSetImageBluePrimary = MagickSetImageBluePrimary(wand : MagickWand*, x : LibC::Double, y : LibC::Double, z : LibC::Double) : Bool
  fun magickSetImageBorderColor = MagickSetImageBorderColor(wand : MagickWand*, border : PixelWand*) : Bool
  fun magickSetImageChannelMask = MagickSetImageChannelMask(wand : MagickWand*, channel_mask : ChannelType) : ChannelType
  fun magickSetImageMask = MagickSetImageMask(wand : MagickWand*, type : PixelMask, clip_mask : MagickWand*) : Bool
  fun magickSetImageColor = MagickSetImageColor(wand : MagickWand*, color : PixelWand*) : Bool
  fun magickSetImageColormapColor = MagickSetImageColormapColor(wand : MagickWand*, index : LibC::SizeT, color : PixelWand*) : Bool
  fun magickSetImageColorspace = MagickSetImageColorspace(wand : MagickWand*, colorspace : ColorspaceType) : Bool
  fun magickSetImageCompose = MagickSetImageCompose(wand : MagickWand*, compose : CompositeOperator) : Bool
  fun magickSetImageCompression = MagickSetImageCompression(wand : MagickWand*, compression : CompressionType) : Bool
  fun magickSetImageCompressionQuality = MagickSetImageCompressionQuality(wand : MagickWand*, quality : LibC::SizeT) : Bool
  fun magickSetImageDelay = MagickSetImageDelay(wand : MagickWand*, delay : LibC::SizeT) : Bool
  fun magickSetImageDepth = MagickSetImageDepth(wand : MagickWand*, depth : LibC::SizeT) : Bool
  fun magickSetImageDispose = MagickSetImageDispose(wand : MagickWand*, dispose : DisposeType) : Bool
  fun magickSetImageEndian = MagickSetImageEndian(wand : MagickWand*, endian : EndianType) : Bool
  fun magickSetImageExtent = MagickSetImageExtent(wand : MagickWand*, columns : LibC::SizeT, rows : LibC::SizeT) : Bool
  fun magickSetImageFilename = MagickSetImageFilename(wand : MagickWand*, filename : LibC::Char*) : Bool
  fun magickSetImageFormat = MagickSetImageFormat(wand : MagickWand*, format : LibC::Char*) : Bool
  fun magickSetImageFuzz = MagickSetImageFuzz(wand : MagickWand*, fuzz : LibC::Double) : Bool
  fun magickSetImageGamma = MagickSetImageGamma(wand : MagickWand*, gamma : LibC::Double) : Bool
  fun magickSetImageGravity = MagickSetImageGravity(wand : MagickWand*, gravity : GravityType) : Bool
  fun magickSetImageGreenPrimary = MagickSetImageGreenPrimary(wand : MagickWand*, x : LibC::Double, y : LibC::Double, z : LibC::Double) : Bool
  fun magickSetImageInterlaceScheme = MagickSetImageInterlaceScheme(wand : MagickWand*, interlace : InterlaceType) : Bool
  fun magickSetImagePixelInterpolateMethod = MagickSetImagePixelInterpolateMethod(wand : MagickWand*, method : PixelInterpolateMethod) : Bool
  fun magickSetImageInterpolateMethod = MagickSetImageInterpolateMethod(wand : MagickWand*, method : PixelInterpolateMethod) : Bool
  fun magickSetImageIterations = MagickSetImageIterations(wand : MagickWand*, iterations : LibC::SizeT) : Bool
  fun magickSetImageMatte = MagickSetImageMatte(wand : MagickWand*, matte : Bool) : Bool
  fun magickSetImageMatteColor = MagickSetImageMatteColor(wand : MagickWand*, alpha : PixelWand*) : Bool
  fun magickSetImageAlpha = MagickSetImageAlpha(wand : MagickWand*, alpha : LibC::Double) : Bool
  fun magickSetImageOrientation = MagickSetImageOrientation(wand : MagickWand*, orientation : OrientationType) : Bool
  fun magickSetImagePage = MagickSetImagePage(wand : MagickWand*, width : LibC::SizeT, height : LibC::SizeT, x : LibC::SSizeT, y : LibC::SSizeT) : Bool
  fun magickSetImagePixelColor = MagickSetImagePixelColor(wand : MagickWand*, x : LibC::SSizeT, y : LibC::SSizeT, color : PixelWand*) : Bool
  fun magickSetImageProgressMonitor = MagickSetImageProgressMonitor(wand : MagickWand*, progress_monitor : MagickProgressMonitor, client_data : Void*) : MagickProgressMonitor
  fun magickSetImageRedPrimary = MagickSetImageRedPrimary(wand : MagickWand*, x : LibC::Double, y : LibC::Double, z : LibC::Double) : Bool
  fun magickSetImageRenderingIntent = MagickSetImageRenderingIntent(wand : MagickWand*, rendering_intent : RenderingIntent) : Bool
  fun magickSetImageResolution = MagickSetImageResolution(wand : MagickWand*, x_resolution : LibC::Double, y_resolution : LibC::Double) : Bool
  fun magickSetImageScene = MagickSetImageScene(wand : MagickWand*, scene : LibC::SizeT) : Bool
  fun magickSetImageTicksPerSecond = MagickSetImageTicksPerSecond(wand : MagickWand*, ticks_per_second : LibC::SSizeT) : Bool
  fun magickSetImageType = MagickSetImageType(wand : MagickWand*, image_type : ImageType) : Bool
  fun magickSetImageUnits = MagickSetImageUnits(wand : MagickWand*, units : ResolutionType) : Bool
  fun magickSetImageVirtualPixelMethod = MagickSetImageVirtualPixelMethod(wand : MagickWand*, method : VirtualPixelMethod) : VirtualPixelMethod
  fun magickSetImageWhitePoint = MagickSetImageWhitePoint(wand : MagickWand*, x : LibC::Double, y : LibC::Double, z : LibC::Double) : Bool
  fun magickShadeImage = MagickShadeImage(wand : MagickWand*, gray : Bool, asimuth : LibC::Double, elevation : LibC::Double) : Bool
  fun magickShadowImage = MagickShadowImage(wand : MagickWand*, alpha : LibC::Double, sigma : LibC::Double, x : LibC::SSizeT, y : LibC::SSizeT) : Bool
  fun magickSharpenImage = MagickSharpenImage(wand : MagickWand*, radius : LibC::Double, sigma : LibC::Double) : Bool
  fun magickShaveImage = MagickShaveImage(wand : MagickWand*, columns : LibC::SizeT, rows : LibC::SizeT) : Bool
  fun magickShearImage = MagickShearImage(wand : MagickWand*, background : PixelWand*, x_shear : LibC::Double, y_shear : LibC::Double) : Bool
  fun magickSigmoidalContrastImage = MagickSigmoidalContrastImage(wand : MagickWand*, sharpen : Bool, alpha : LibC::Double, beta : LibC::Double) : Bool
  fun magickSimilarityImage = MagickSimilarityImage(wand : MagickWand*, reference : MagickWand*, metric : MetricType, similarity_threshold : LibC::Double, offset : RectangleInfo*, similarity : LibC::Double*) : MagickWand*
  fun magickSketchImage = MagickSketchImage(wand : MagickWand*, radius : LibC::Double, sigma : LibC::Double, angle : LibC::Double) : Bool
  fun magickSmushImages = MagickSmushImages(wand : MagickWand*, stack : Bool, offset : LibC::SSizeT) : MagickWand*
  fun magickSolarizeImage = MagickSolarizeImage(wand : MagickWand*, threshold : LibC::Double) : Bool
  fun magickSparseColorImage = MagickSparseColorImage(wand : MagickWand*, method : SparseColorMethod, number_arguments : LibC::SizeT, arguments : LibC::Double*) : Bool
  fun magickSpliceImage = MagickSpliceImage(wand : MagickWand*, width : LibC::SizeT, height : LibC::SizeT, x : LibC::SSizeT, y : LibC::SSizeT) : Bool
  fun magickSpreadImage = MagickSpreadImage(wand : MagickWand*, method : PixelInterpolateMethod, radius : LibC::Double) : Bool
  fun magickStatisticImage = MagickStatisticImage(wand : MagickWand*, type : StatisticType, width : LibC::SizeT, height : LibC::SizeT) : Bool
  fun magickSteganoImage = MagickSteganoImage(wand : MagickWand*, watermark_wand : MagickWand*, offset : LibC::SSizeT) : MagickWand*
  fun magickStereoImage = MagickStereoImage(wand : MagickWand*, offset_wand : MagickWand*) : MagickWand*
  fun magickStripImage = MagickStripImage(wand : MagickWand*) : Bool
  fun magickSwirlImage = MagickSwirlImage(wand : MagickWand*, degrees : LibC::Double, method : PixelInterpolateMethod) : Bool
  fun magickTextureImage = MagickTextureImage(wand : MagickWand*, texture_wand : MagickWand*) : MagickWand*
  fun magickThresholdImage = MagickThresholdImage(wand : MagickWand*, threshold : LibC::Double) : Bool
  fun magickThresholdImageChannel = MagickThresholdImageChannel(wand : MagickWand*, channel : ChannelType, threshold : LibC::Double) : Bool
  fun magickThumbnailImage = MagickThumbnailImage(wand : MagickWand*, columns : LibC::SizeT, rows : LibC::SizeT) : Bool
  fun magickTintImage = MagickTintImage(wand : MagickWand*, tint : PixelWand*, blend : PixelWand*) : Bool
  fun magickTransformImageColorspace = MagickTransformImageColorspace(wand : MagickWand*, colorspace : ColorspaceType) : Bool
  fun magickTransparentPaintImage = MagickTransparentPaintImage(wand : MagickWand*, target : PixelWand*, alpha : LibC::Double, fuzz : LibC::Double, invert : Bool) : Bool
  fun magickTransposeImage = MagickTransposeImage(wand : MagickWand*) : Bool
  fun magickTransverseImage = MagickTransverseImage(wand : MagickWand*) : Bool
  fun magickTrimImage = MagickTrimImage(wand : MagickWand*, fuzz : LibC::Double) : Bool
  fun magickUniqueImageColors = MagickUniqueImageColors(wand : MagickWand*) : Bool
  fun magickUnsharpMaskImage = MagickUnsharpMaskImage(wand : MagickWand*, radius : LibC::Double, sigma : LibC::Double, gain : LibC::Double, threshold : LibC::Double) : Bool
  fun magickVignetteImage = MagickVignetteImage(wand : MagickWand*, radius : LibC::Double, sigma : LibC::Double, x : LibC::SSizeT, y : LibC::SSizeT) : Bool
  fun magickWaveImage = MagickWaveImage(wand : MagickWand*, amplitude : LibC::Double, wave_length : LibC::Double, method : PixelInterpolateMethod) : Bool
  fun magickWaveletDenoiseImage = MagickWaveletDenoiseImage(wand : MagickWand*, threshold : LibC::Double, softness : LibC::Double) : Bool
  fun magickWhiteThresholdImage = MagickWhiteThresholdImage(wand : MagickWand*, threshold : PixelWand*) : Bool
  fun magickWriteImage = MagickWriteImage(wand : MagickWand*, filename : LibC::Char*) : Bool
  fun magickWriteImageFile = MagickWriteImageFile(wand : MagickWand*, file : LibStd::File*) : Bool
  fun magickWriteImages = MagickWriteImages(wand : MagickWand*, filename : LibC::Char*, adjoin : Bool) : Bool
  fun magickWriteImagesFile = MagickWriteImagesFile(wand : MagickWand*, file : LibStd::File*) : Bool
end
