lib LibMagick
  fun clearPixelWand = ClearPixelWand(wand : PixelWand*) : Void
  fun clonePixelWand = ClonePixelWand(wand : PixelWand*) : PixelWand*
  fun clonePixelWands = ClonePixelWands(wands : PixelWand**, number_wands : LibC::SizeT) : PixelWand**
  fun destroyPixelWand = DestroyPixelWand(wand : PixelWand*) : PixelWand*
  fun destroyPixelWands = DestroyPixelWands(wand : PixelWand**, number_wands : LibC::SizeT) : PixelWand**
  fun isPixelWandSimilar = IsPixelWandSimilar(p : PixelWand*, q : PixelWand*, fuzz : LibC::Double) : Bool
  fun isPixelWand = IsPixelWand(wand : PixelWand*) : Bool
  fun newPixelWand = NewPixelWand : PixelWand*
  fun newPixelWands = NewPixelWands(number_wands : LibC::SizeT) : PixelWand**
  fun pixelClearException = PixelClearException(wand : PixelWand*) : Bool
  fun pixelGetAlpha = PixelGetAlpha(wand : PixelWand*) : LibC::Double
  fun pixelGetAlphaQuantum = PixelGetAlphaQuantum(wand : PixelWand*) : Quantum
  fun pixelGetBlack = PixelGetBlack(wand : PixelWand*) : LibC::Double
  fun pixelGetBlackQuantum = PixelGetBlackQuantum(wand : PixelWand*) : Quantum
  fun pixelGetBlue = PixelGetBlue(wand : PixelWand*) : LibC::Double
  fun pixelGetBlueQuantum = PixelGetBlueQuantum(wand : PixelWand*) : Quantum
  fun pixelGetColorAsString = PixelGetColorAsString(wand : PixelWand*) : LibC::Char*
  fun pixelGetColorAsNormalizedString = PixelGetColorAsNormalizedString(wand : PixelWand*) : LibC::Char*
  fun pixelGetColorCount = PixelGetColorCount(wand : PixelWand*) : LibC::SizeT
  fun pixelGetCyan = PixelGetCyan(wand : PixelWand*) : LibC::Double
  fun pixelGetCyanQuantum = PixelGetCyanQuantum(wand : PixelWand*) : Quantum
  fun pixelGetException = PixelGetException(wand : PixelWand*, severity : ExceptionType*) : LibC::Char*
  fun pixelGetExceptionType = PixelGetExceptionType(wand : PixelWand*) : ExceptionType
  fun pixelGetFuzz = PixelGetFuzz(wand : PixelWand*) : LibC::Double
  fun pixelGetGreen = PixelGetGreen(wand : PixelWand*) : LibC::Double
  fun pixelGetGreenQuantum = PixelGetGreenQuantum(wand : PixelWand*) : Quantum
  fun pixelGetHSL = PixelGetHSL(wand : PixelWand*, hue : LibC::Double*, saturation : LibC::Double*, lightness : LibC::Double*) : Void
  fun pixelGetIndex = PixelGetIndex(wand : PixelWand*) : Quantum
  fun pixelGetMagenta = PixelGetMagenta(wand : PixelWand*) : LibC::Double
  fun pixelGetMagentaQuantum = PixelGetMagentaQuantum(wand : PixelWand*) : Quantum
  fun pixelGetMagickColor = PixelGetMagickColor(wand : PixelWand*, color : PixelInfo*) : Void
  fun pixelGetPixel = PixelGetPixel(wand : PixelWand*) : PixelInfo
  fun pixelGetQuantumPacket = PixelGetQuantumPacket(wand : PixelWand*, packet : PixelInfo*) : Void
  fun pixelGetQuantumPixel = PixelGetQuantumPixel(image : Image*, wand : PixelWand*, pixel : Quantum*) : Void
  fun pixelGetRed = PixelGetRed(wand : PixelWand*) : LibC::Double
  fun pixelGetRedQuantum = PixelGetRedQuantum(wand : PixelWand*) : Quantum
  fun pixelGetYellow = PixelGetYellow(wand : PixelWand*) : LibC::Double
  fun pixelGetYellowQuantum = PixelGetYellowQuantum(wand : PixelWand*) : Quantum
  fun pixelSetAlpha = PixelSetAlpha(wand : PixelWand*, alpha : LibC::Double) : Void
  fun pixelSetAlphaQuantum = PixelSetAlphaQuantum(wand : PixelWand*, alpha : Quantum) : Void
  fun pixelSetBlack = PixelSetBlack(wand : PixelWand*, black : LibC::Double) : Void
  fun pixelSetBlackQuantum = PixelSetBlackQuantum(wand : PixelWand*, black : Quantum) : Void
  fun pixelSetBlue = PixelSetBlue(wand : PixelWand*, blue : LibC::Double) : Void
  fun pixelSetBlueQuantum = PixelSetBlueQuantum(wand : PixelWand*, blue : Quantum) : Void
  fun pixelSetColor = PixelSetColor(wand : PixelWand*, color : LibC::Char*) : Bool
  fun pixelSetColorCount = PixelSetColorCount(wand : PixelWand*, count : LibC::SizeT) : Void
  fun pixelSetColorFromWand = PixelSetColorFromWand(wand : PixelWand*, color : PixelWand*) : Void
  fun pixelSetCyan = PixelSetCyan(wand : PixelWand*, cyan : LibC::Double) : Void
  fun pixelSetCyanQuantum = PixelSetCyanQuantum(wand : PixelWand*, cyan : Quantum) : Void
  fun pixelSetFuzz = PixelSetFuzz(wand : PixelWand*, fuzz : LibC::Double) : Void
  fun pixelSetGreen = PixelSetGreen(wand : PixelWand*, green : LibC::Double) : Void
  fun pixelSetGreenQuantum = PixelSetGreenQuantum(wand : PixelWand*, green : Quantum) : Void
  fun pixelSetHSL = PixelSetHSL(wand : PixelWand*, hue : LibC::Double, saturation : LibC::Double, lightness : LibC::Double) : Void
  fun pixelSetIndex = PixelSetIndex(wand : PixelWand*, index : Quantum) : Void
  fun pixelSetMagenta = PixelSetMagenta(wand : PixelWand*, magenta : LibC::Double) : Void
  fun pixelSetMagentaQuantum = PixelSetMagentaQuantum(wand : PixelWand*, magenta : Quantum) : Void
  fun pixelSetPixelColor = PixelSetPixelColor(wand : PixelWand*, color : PixelInfo*) : Void
  fun pixelSetQuantumPixel = PixelSetQuantumPixel(image : Image*, pixel : Quantum*, wand : PixelWand*) : Void
  fun pixelSetRed = PixelSetRed(wand : PixelWand*, red : LibC::Double) : Void
  fun pixelSetRedQuantum = PixelSetRedQuantum(wand : PixelWand*, red : Quantum) : Void
  fun pixelSetYellow = PixelSetYellow(wand : PixelWand*, yellow : LibC::Double) : Void
  fun pixelSetYellowQuantum = PixelSetYellowQuantum(wand : PixelWand*, yellow : Quantum) : Void
end
