lib LibMagick
  fun acquireImage = AcquireImage(image_info : ImageInfo*, exception : ExceptionInfo*) : Image*
  fun acquireImageInfo = AcquireImageInfo : ImageInfo*
  fun acquireNextImage = AcquireNextImage(image_info : ImageInfo*, image : Image*, exception : ExceptionInfo*) : Void
  fun appendImages = AppendImages(images : Image*, stack : Bool, exception : ExceptionInfo*) : Image*
  fun catchImageException = CatchImageException(image : Image*) : ExceptionType
  fun clipImage = ClipImage(image : Image*, exception : ExceptionInfo*) : Bool
  fun clipImagePath = ClipImagePath(image : Image*, pathname : LibC::Char*, inside : Bool, exception : ExceptionInfo*) : Bool
  fun cloneImage = CloneImage(image : Image*, columns : LibC::SizeT, rows : LibC::SizeT, detach : Bool, exception : ExceptionInfo*) : Image*
  fun cloneImageInfo = CloneImageInfo(image_info : ImageInfo*) : ImageInfo*
  fun copyImagePixels = CopyImagePixels(image : Image*, source_image : Image*, geometry : RectangleInfo*, offset : OffsetInfo*, exception : ExceptionInfo*) : Bool
  fun destroyImage = DestroyImage(image : Image*) : Image*
  fun destroyImageInfo = DestroyImageInfo(image_info : ImageInfo*) : ImageInfo*
  fun disassociateImageStream = DisassociateImageStream(image : Image*) : Void
  fun getImageInfo = GetImageInfo(image_info : ImageInfo*) : Void
  fun getImageInfoFile = GetImageInfoFile(image_info : ImageInfo*) : LibStd::File*
  fun getImageMask = GetImageMask(image : Image*, type : PixelMask, exception : ExceptionInfo*) : Image*
  fun getImageReferenceCount = GetImageReferenceCount(image : Image*) : LibC::SSizeT
  fun getImageVirtualPixelMethod = GetImageVirtualPixelMethod(image : Image*) : VirtualPixelMethod
  fun interpretImageFilename = InterpretImageFilename(image_info : ImageInfo*, image : Image*, format : LibC::Char*, value : LibC::Int, filename : LibC::Char*, exception : ExceptionInfo*) : LibC::SizeT
  fun isHighDynamicRangeImage = IsHighDynamicRangeImage(image : Image*, exception : ExceptionInfo*) : Bool
  fun isImageObject = IsImageObject(image : Image*) : Bool
  fun isTaintImage = IsTaintImage(image : Image*) : Bool
  fun modifyImage = ModifyImage(image : Image**, exception : ExceptionInfo*) : Bool
  fun newMagickImage = NewMagickImage(image_info : ImageInfo*, width : LibC::SizeT, height : LibC::SizeT, background : PixelInfo*, exception : ExceptionInfo*) : Image*
  fun referenceImage = ReferenceImage(image : Image*) : Image*
  fun resetImagePage = ResetImagePage(image : Image*, page : LibC::Char*) : Bool
  fun resetImagePixels = ResetImagePixels(image : Image*, exception : ExceptionInfo*) : Bool
  fun setImageAlpha = SetImageAlpha(image : Image*, alpha : Quantum, exception : ExceptionInfo*) : Bool
  fun setImageBackgroundColor = SetImageBackgroundColor(image : Image*, exception : ExceptionInfo*) : Bool
  fun setImageChannelMask = SetImageChannelMask(image : Image*, channel_mask : ChannelType) : ChannelType
  fun setImageColor = SetImageColor(image : Image*, color : PixelInfo*, exception : ExceptionInfo*) : Bool
  fun setImageStorageClass = SetImageStorageClass(image : Image*, storage_class : ClassType, exception : ExceptionInfo*) : Bool
  fun setImageExtent = SetImageExtent(image : Image*, columns : LibC::SizeT, rows : LibC::SizeT, exception : ExceptionInfo*) : Bool
  fun setImageInfo = SetImageInfo(image_info : ImageInfo*, frames : LibC::UInt, exception : ExceptionInfo*) : Bool
  fun setImageInfoBlob = SetImageInfoBlob(image_info : ImageInfo*, blob : Void*, length : LibC::SizeT) : Void
  fun setImageInfoCustomStream = SetImageInfoCustomStream(image_info : ImageInfo*, custom_stream : CustomStreamInfo*) : Void
  fun setImageInfoFile = SetImageInfoFile(image_info : ImageInfo*, file : LibStd::File*) : Void
  fun setImageMask = SetImageMask(image : Image*, type : PixelMask, mask : Image*, exception : ExceptionInfo*) : Bool
  fun setImageRegionMask = SetImageRegionMask(image : Image*, type : PixelMask, region : RectangleInfo*, exception : ExceptionInfo*) : Bool
  fun setImageVirtualPixelMethod = SetImageVirtualPixelMethod(image : Image*, virtual_pixel_method : VirtualPixelMethod, exception : ExceptionInfo*) : VirtualPixelMethod
  fun smushImages = SmushImages(images : Image*, stack : Bool, offset : LibC::SSizeT, exception : ExceptionInfo*) : Image*
  fun stripImage = StripImage(image : Image*, exception : ExceptionInfo*) : Bool
  fun syncImage = SyncImage(image : Image*, exception : ExceptionInfo*) : Bool
  fun syncImagesSettings = SyncImagesSettings(image_info : ImageInfo*, images : Image*, exception : ExceptionInfo*) : Bool
  fun syncImageSettings = SyncImageSettings(image_info : ImageInfo*, image : Image*, exception : ExceptionInfo*) : Bool
end
